### ISSUE TITLE
content-type test

### ISSUE THREAD

**Issue by Charle42** [schul-cloud/schul_cloud_search_tests#11]
The function [test_the_content_type_is_from_the_jsonapi](https://github.com/schul-cloud/schul_cloud_search_tests/blob/master/schul_cloud_search_tests/search_tests/test_response.py) test the content-type of the response.

**The problem **, only accept "application/vnd.api+json" but some frameworks like Nodejs Express add automatically " ; charset:utf-8 " to the content-type.
Utf-8  is the standard encoding and is not necessary to send this. 

**Idea** accept either content-types

**Comment by niccokunzmann** [comment]
Thanks! True. Would you like to work on it?

**Comment by niccokunzmann** [comment]
I agree: 

Quote from [JSONAPI](http://jsonapi.org/format/#content-negotiation-clients):

    Clients MUST ignore any parameters for the application/vnd.api+json media type received in the Content-Type header of response documents.

**Comment by niccokunzmann** [comment]
[Here](https://github.com/schul-cloud/schul_cloud_search_tests/blob/master/schul_cloud_search_tests/tests/test_headers.py), we should add a test with different Content-Types returned which would be accepted.

**Comment by niccokunzmann** [comment]
@Charle42 You can check. When Travis is done: https://travis-ci.org/schul-cloud/schul_cloud_search_tests/builds done.
