### ISSUE TITLE
<h1>Critical error while processing request: /</h1>

### ISSUE THREAD

**Issue by Charle42** [schul-cloud/schul_cloud_search_tests#13]
```
______ test_detect_invalid_accept_headers[application/vnd.api+json; v=1] _______
self = <json.decoder.JSONDecoder object at 0x7fbdb3ab0240>
s = '<h1>Critical error while processing request: /</h1>', idx = 0
    def raw_decode(self, s, idx=0):
        """Decode a JSON document from ``s`` (a ``str`` beginning with
            a JSON document) and return a 2-tuple of the Python
            representation and the index in ``s`` where the document ended.
    
            This can be used to decode a JSON document from a string that may
            have extraneous data at the end.
    
            """
        try:
>           obj, end = self.scan_once(s, idx)
E           StopIteration: 0
/opt/python/3.5.3/lib/python3.5/json/decoder.py:355: StopIteration
```
He try to parse html content as Json. 
Why and when return the search engine this s as body?

**Comment by niccokunzmann** [comment]
I think, this happens, if there is json expected but no content delivered. Which command do you use to create this error? Is this the full stack trace?

**Comment by Charle42** [comment]
no this is not the full strack trace.
```
=================================== FAILURES ===================================
______ test_detect_invalid_accept_headers[application/vnd.api+json; v=1] _______
self = <json.decoder.JSONDecoder object at 0x7f884d7da1d0>
s = '<h1>Critical error while processing request: /</h1>', idx = 0
    def raw_decode(self, s, idx=0):
        """Decode a JSON document from ``s`` (a ``str`` beginning with
            a JSON document) and return a 2-tuple of the Python
            representation and the index in ``s`` where the document ended.
    
            This can be used to decode a JSON document from a string that may
            have extraneous data at the end.
    
            """
        try:
>           obj, end = self.scan_once(s, idx)
E           StopIteration: 0
/opt/python/3.5.3/lib/python3.5/json/decoder.py:355: StopIteration
During handling of the above exception, another exception occurred:
validateRequest = <function validateRequest.<locals>.validateRequest at 0x7f884ab642f0>
invalid_accept_header = 'application/vnd.api+json; v=1'
    @mark.parametrize("invalid_accept_header", INVALID_ACCEPT_HEADERS)
    def test_detect_invalid_accept_headers(validateRequest, invalid_accept_header):
>       validateRequest(headers={"Accept":invalid_accept_header})
../../../.local/lib/python3.5/site-packages/schul_cloud_search_tests/search/test_headers.py:13: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
../../../.local/lib/python3.5/site-packages/schul_cloud_search_tests/search/conftest.py:100: in validateRequest
    result_json = result.json()
../../../.local/lib/python3.5/site-packages/requests/models.py:894: in json
    return complexjson.loads(self.text, **kwargs)
/opt/python/3.5.3/lib/python3.5/json/__init__.py:319: in loads
    return _default_decoder.decode(s)
/opt/python/3.5.3/lib/python3.5/json/decoder.py:339: in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
self = <json.decoder.JSONDecoder object at 0x7f884d7da1d0>
s = '<h1>Critical error while processing request: /</h1>', idx = 0
    def raw_decode(self, s, idx=0):
        """Decode a JSON document from ``s`` (a ``str`` beginning with
            a JSON document) and return a 2-tuple of the Python
            representation and the index in ``s`` where the document ended.
    
            This can be used to decode a JSON document from a string that may
            have extraneous data at the end.
    
            """
        try:
            obj, end = self.scan_once(s, idx)
        except StopIteration as err:
>           raise JSONDecodeError("Expecting value", s, err.value) from None
E           json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
/opt/python/3.5.3/lib/python3.5/json/decoder.py:357: JSONDecodeError
---------------------------- Captured stderr setup -----------------------------
Bottle v0.12.13 server starting up (using StoppableWSGIRefServerAdapter())...
Listening on http://127.0.0.1:0/
Hit Ctrl-C to quit.
----------------------------- Captured stdout call -----------------------------
query string: Q=einstein
```

and I use this command:
```python3 -m schul_cloud_search_tests.search --url=http://localhost:3000/v1```

**Comment by niccokunzmann** [comment]
What is the output if you request 

    http://localhost:3000/v1?Q=einstein

?
Should we output the curl command which can be run from the command line to reproduce the request?
Would that be a good debugging method?
Should it be /v1/search?

**Comment by niccokunzmann** [comment]
Okay, I see. The error is in the search test proxy. When it has an internal error, it just aborts with the usual html page.

(1) We can create a try except around this line: 

    result_json = result.json()

And if it fails, we can print the whole content which is expected to be json

(2) We can make it so server errors are jsonapi compatible, too. 

(3) You [run the proxy against your search engine](https://github.com/schul-cloud/schul_cloud_search_tests#usage-as-proxy) and print the whole error stack trace. We fix it for this bug but need to do the same debugging every time an internal server error occurs in the proxy.

Which option would you prefer?

**Comment by niccokunzmann** [comment]
I think, there must be still more output. Looking at line
100:

        try:
            result_json = result.json()
        except:
            print("Requesting", query, "->", url)
            raise

If there is this error, it prints something.
You can capture the whole output and paste that?

**Comment by niccokunzmann** [comment]
@Charle42 You can link to the tests that do not work for you. I will be looking at this: https://travis-ci.org/schul-cloud/wikimedia-content-adapter/builds/261016036

- This is the line which creates the error message: https://github.com/bottlepy/bottle/blob/master/bottle.py#L1116
  DEBUG seems not to be set to True, so no further output is given. I will see what I can do aout this.

**Comment by niccokunzmann** [comment]
@Charle42 You can install these changes using `schul-cloud-search-tests==1.0.75`.

**Comment by niccokunzmann** [comment]
I see here https://travis-ci.org/schul-cloud/wikimedia-content-adapter/builds/263493569 that this error is not solved by v1.0.75

**Comment by niccokunzmann** [comment]
I will set it up and see what I can find.

**Comment by niccokunzmann** [comment]
I can see this error: 

```
self = <jsonschema.validators.RefResolver object at 0x7f5d8b350780>
url = 'https://github.com/schul-cloud/resources-api-v1/raw/master/schemas/license/license.json'

    def resolve_from_url(self, url):
        url, fragment = urldefrag(url)
        try:
            document = self.store[url]
        except KeyError:
            try:
                document = self.resolve_remote(url)
            except Exception as exc:
>               raise RefResolutionError(exc)
E               jsonschema.exceptions.RefResolutionError: Expecting value: line 1 column 1 (char 0)

ENV/lib/python3.5/site-packages/jsonschema/validators.py:385: RefResolutionError
```
Which results from you setting the license attribute but the license attribute can not be verified.
When this issue is closed: https://github.com/schul-cloud/resources-api-v1/issues/5, we can update the search tests and resources tests to the latest version and it should work.

This can be reproduced by 

1. running your server
2. running `python3 -m schul_cloud_search_tests.proxy http://localhost:3000/v1`
3. running `$ curl -i http://localhost:8081/v1/search?Q=einstein`

@Charle42 Would you like to help me with https://github.com/schul-cloud/resources-api-v1/issues/5?

**Comment by niccokunzmann** [comment]
@Charle42 now, a new version is out. Could you have a look if the error still exists or if there are new errors?

**Comment by niccokunzmann** [comment]
https://travis-ci.org/schul-cloud/wikimedia-content-adapter/builds/267540616#L944
Dieser Fehler wird immenoch angezeigt.

**Comment by Charle42** [comment]
ich hab die gesamte Nachricht gefunden 
``` html
<h1>Critical error while processing request: /v1/search</h1><h2>Error:</h2>
<pre>
AssertionError(&#039;Hop-by-hop headers not allowed&#039;,)
</pre>
<h2>Traceback:</h2>
<pre>
Traceback (most recent call last):
  File &quot;/home/fabien/.local/lib/python3.5/site-packages/bottle.py&quot;, line 960, in wsgi
    start_response(response._status_line, response.headerlist)
  File &quot;/usr/lib/python3.5/wsgiref/handlers.py&quot;, line 236, in start_response
    assert not is_hop_by_hop(name),&quot;Hop-by-hop headers not allowed&quot;
AssertionError: Hop-by-hop headers not allowed

</pre>
```
Wenn ich die Anfragen an den proxy laufen lasse bekomme ich nur diese Antwort.
Hat was mit den `hop-by-hop headers`zu tun ?

**Comment by niccokunzmann** [comment]
https://stackoverflow.com/a/26440343/1320237 sagt, dass da einige Header ein Problem haben.
Ich versuche das mal zu überprüfen. In PR #17 habe ich die weitergeleiteten Header verändert. Vielleicht gebe ich mal keine weiter und schaue, ob das was hilft.

**Comment by niccokunzmann** [comment]
Das ist der einzige Test, der fehlschlägt und diese Error-output generiert:
https://github.com/schul-cloud/schul_cloud_search_tests/blob/master/schul_cloud_search_tests/search/test_headers.py#L12

**Comment by niccokunzmann** [comment]
So kann man nur diesen einen Test ausführen: 

    python -m schul_cloud_search_tests.search --url=http://localhost:3000/v1 -k test_detect_invalid_accept_headers

**Comment by niccokunzmann** [comment]
Das ist ein Problem, das du nicht erzeugst. Das macht das proxy.py programm.

**Comment by niccokunzmann** [comment]
Wenn der Build durchgelaufen ist, kannst du das mit Version 1.0.85 mal testen: https://travis-ci.org/schul-cloud/schul_cloud_search_tests/builds/275075812

**Comment by Charle42** [comment]
:+1: 
local läufts 

travis arbeitet noch

**Comment by niccokunzmann** [comment]
Hm. ne tut mir leid, ich habe noch einen Fehler eingebaut.

**Comment by niccokunzmann** [comment]
Jetzt bin ich mir wieder mal sicher, dass es jetzt klappen könnte.
https://travis-ci.org/schul-cloud/schul_cloud_search_tests/builds/275100911
