### ISSUE TITLE
Create Dockerfile for Python

### ISSUE THREAD

**Issue by niccokunzmann** [schul-cloud/schul_cloud_search_tests#5]
To run this Python process on a server, we use [Docker](http://docker.com).
Create a "Dockerfile" for this python service.

To close the issue all of this must be done, but you can do only part of it.
- [x] the packages are installed
- [x] the license is copied to the package folder
- [x] the requirements are installed
- [x] `python3 -m schul_cloud_search_tests.proxy` is the command which receives the additional arguments

You can view an example file [here](https://github.com/schul-cloud/schul_cloud_resources_server_tests/blob/master/Dockerfile).

**Comment by keqiang** [comment]
I recently started using Docker and am interested in creating this Dockerfile.

So I understand the Dockerfile should begin with 

`FROM python:3 `

Here I should switch to the app dir probably?

`WORKDIR /usr/src/schul_cloud_search_tests`

then install the requirements by

```
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt
```

then install the test app, should I copy the project folder directly or use `pip install --user schul-cloud-search-tests?`

I'm still looking at how to pass docker container arguments to our .proxy command. I guess that's how we start the tests. 

If this is the right direction, I will try to add the Dockerfile. Thanks.

**Comment by niccokunzmann** [comment]
> So I understand the Dockerfile should begin with
>
> |FROM python:3|
>
|Yes, I think so, too.|
>
> Here I should switch to the app dir probably?
>
> |WORKDIR /usr/src/schul_cloud_search_tests|
>
|You can use any directory you think is okay. This one is ok.|
>
> then install the requirements by
>
> |COPY requirements.txt ./ RUN pip install --no-cache-dir -r
> requirements.txt|
|I would like the requirements.txt to be in the app directory. This way,
the code download because of the AGPL license allows downloading the
requirements.txt file, too.
|
>
> then install the test app, should I copy the project folder directly
> or use |pip install --user schul-cloud-search-tests?|
>
If you use the copied folder, requirements.txt and the LICENSE file can
be added to the module and downloaded together with the source code.
>
> I'm still looking at how to pass docker run arguments to the our
> .proxy command, I guess that's how we start the tests.
>
I think, the arguments are automatically appended if you set CMD in the
Dockerfile. Then, the container is started with `docker run
CONTAINER_NAME ARGUMENT1 ARGUMENT2`
>
> If this is the right direction, I will try to add the Dockerfile. Thanks.
>
I believe, you are going in the right direction. If you like, you can
also create a pull-request and if you have questions about the code, we
can discuss it there, too.

**Comment by keqiang** [comment]
Thanks for the reply. Will create a pull request.

**Comment by niccokunzmann** [comment]
@keqiang I started an automated build. https://hub.docker.com/r/schulcloud/schul_cloud_search_tests/builds/

**Comment by niccokunzmann** [comment]
@keqiang Thanks, this is working fine!
![grafik](https://user-images.githubusercontent.com/564768/27772015-edc70c64-5f5a-11e7-8ba8-dfc664ec3eb0.png)
c6f3c5d makes Python print everything (host and port, ...). If you use Python in a container, you might want to remember this.
